### ISSUE TITLE
Nom des colonnes

### ISSUE THREAD

**Issue by chloe-pellen** [sudweb/talks#24]

**Comment by borisschapira** [comment]
@chloe-pellen tu as trouvé, du coup ? Sinon je te sors un exemple dès que je re-touche un ordi, dans l'après-midi.

**Comment by chloe-pellen** [comment]
Oui j'ai trouvé, voici la configuration des fields qui correspond à l'exemple donné dans le readme :
    ```"fields": {																
        "name": "prenom_et_nom",
        "title": "titre_de_ta_presentation",
        "description": "description_de_ta_presentation",
        "timestamp": "timestamp"
    }```

J'ai ensuite eu un pb d'activation de l'api Google People. Tout semble fonctionner, c'est top ! merci

**Comment by borisschapira** [comment]
👍 

De notre côté, J-5 avant qu'on s'en serve plus activement ;)

**Comment by chloe-pellen** [comment]
Super ! On envisage de l'utiliser pour les UXDAYS, merci en tout cas de
l'avoir publié ;)

Le 11 févr. 2018 19:39, "Boris SCHAPIRA" <notifications@github.com> a
écrit :
